name: RPM Build rocky8
on:
    push:
      # Sequence of patterns matched against refs/tags
      tags:
        - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Package RPM and SRPM
      uses: xmidt-org/rpm-package-action@v1
      with:
        path: .
        spec: slurm-job-exporter-el8.spec
        distro: rocky-8

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Rocky 8 binary RPM
        path: output/
