name: RPM Build rocky8
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Package RPM and SRPM
      uses: xmidt-org/rpm-package-action@v1
      with:
        path: .
        spec: slurm-job-exporter-el8.spec
        distro: rocky-8

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: output/*
